### ISSUE TITLE
sg-core crashing during high volume tests

### ISSUE THREAD

**Issue by csibbitt** [infrawatch/sg-core#57]
While running a test where I drive 100M logs into the system as fast as possible (via the amqp sg-bridge), I was able to reliably crash the sg-core with this stack

```
2021-06-24 16:53:00 [INFO] storing events and(or) logs to Elasticsearch. [plugin: elasticsearch, url: https://elasticsearch-es-http.service-telemetry.svc.cluster.local:9200]
2021-06-24 16:53:00 [INFO] socket listening on /tmp/smartgateway [plugin: socket]
panic: interface conversion: interface {} is nil, not []string

goroutine 175109 [running]:
github.com/infrawatch/sg-core/plugins/application/elasticsearch.(*Elasticsearch).ReceiveEvent(0xc0002d1110, 0xc00138cab0, 0x21, 0x41d8352e1bc00000, 0x2, 0xc0013f6280, 0xf, 0x2, 0xc0013b3260, 0x0, ...)
        /go/src/github.com/infrawatch/sg-core/plugins/application/elasticsearch/main.go:96 +0x87f
github.com/infrawatch/sg-core/pkg/bus.(*EventBus).Publish.func1(0xc00138cab0, 0x21, 0x41d8352e1bc00000, 0x2, 0xc0013f6280, 0xf, 0x2, 0xc0013b3260, 0x0, 0xc001390ca0, ...)
        /go/src/github.com/infrawatch/sg-core/pkg/bus/bus.go:35 +0x62
created by github.com/infrawatch/sg-core/pkg/bus.(*EventBus).Publish
        /go/src/github.com/infrawatch/sg-core/pkg/bus/bus.go:34 +0xbd
```

**Comment by csibbitt** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1975951
